# Generated by Django 5.1.4 on 2024-12-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_address_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
